// src/components/atom/Decrypt.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { expectMasterKey } from '../../state';
import { decryptTextSymFromTRPC, importKeyFromTRPC } from '../../common/crypto-trpc';
import ErrorMessage from './ErrorMessage.vue';

const props = defineProps<{
	data: string,
	iv: string,
	decrypt: Decrypt
}>()

type Decrypt =
	// The data is encrypted with the Master Key
	| { with: 'masterKey' }
	// Provided CryptoKey
	| { with: 'direct'; key: CryptoKey }
	// Plain text JWK key
	| { with: 'jwk'; content: string }
	// JWK symmetryc key encrypted with the Master Key
	| { with: 'jwkMK'; content: string; iv: string }

async function getKey(key: Decrypt): Promise<CryptoKey | Error> {
	if (key.with === 'direct') {
		return key.key
	}

	if (key.with === 'jwk' || key.with === 'jwkMK') {
		// const existing = importedMKKeys.get(key.content)

		// if (existing) {
		// 	return existing
		// }
	}

	if (key.with === 'masterKey' || key.with === 'jwkMK') {
		const masterKey = await expectMasterKey()

		if (key.with === 'masterKey') {
			return masterKey
		}

		const keyJWK = await decryptTextSymFromTRPC(key.content, key.iv, masterKey)

		if (keyJWK instanceof Error) {
			return new Error('Failed to decode the second layer encryption key')
		}

		key = { with: 'jwk', content: keyJWK }
	}

	const imported = await importKeyFromTRPC(key.content, 'sym')

	if (imported instanceof Error) {
		return new Error('Failed to import the provided key')
	}

	// TODO: store in cache

	return imported
}

const error = ref('')
const display = ref('')

onMounted(async () => {
	const key = await getKey(props.decrypt)

	if (key instanceof Error) {
		error.value = key.message
		return
	}

	const result = await decryptTextSymFromTRPC(props.data, props.iv, key)

	if (result instanceof Error) {
		error.value = result.message
	} else {
		display.value = result
	}
})
</script>

<template>
	<ErrorMessage v-if="error" :message="error" />

	{{ display }}
</template>

// src/components/atom/Decrypt.tsx
import { createSignal, onMount, Show } from 'solid-js'
import { decryptTextSymFromTRPC, importKeyFromTRPC } from '../../common/crypto-trpc'
import { expectMasterKey, importedMKKeys } from '../../state'
import { ErrorMessage } from './ErrorMessage'

export type DecryptProps = {
	data: string
	iv: string
	decrypt: DecryptPropsKey
}

export type DecryptPropsKey =
	// The data is encrypted with the Master Key
	| { with: 'masterKey' }
	// Provided CryptoKey
	| { with: 'direct'; key: CryptoKey }
	// Plain text JWK key
	| { with: 'jwk'; content: string }
	// JWK symmetryc key encrypted with the Master Key
	| { with: 'jwkMK'; content: string; iv: string }

export const Decrypt = ({ data, iv, decrypt }: DecryptProps) => {
	const [error, setError] = createSignal('')
	const [result, setResult] = createSignal('')

	onMount(async () => {
		const key = await getKey(decrypt)

		if (key instanceof Error) {
			setError(key.message)
			return
		}

		const result = await decryptTextSymFromTRPC(data, iv, key)

		if (result instanceof Error) {
			setError(result.message)
		} else {
			setResult(result)
		}
	})

	return (
		<>
			<Show when={error()}>
				<ErrorMessage message={error()} inline />
			</Show>
			<Show when={result()}>
				<span>{result}</span>
			</Show>
		</>
	)
}

async function getKey(key: DecryptPropsKey): Promise<CryptoKey | Error> {
	if (key.with === 'direct') {
		return key.key
	}

	if (key.with === 'jwk' || key.with === 'jwkMK') {
		const existing = importedMKKeys.get(key.content)

		if (existing) {
			return existing
		}
	}

	if (key.with === 'masterKey' || key.with === 'jwkMK') {
		const masterKey = await expectMasterKey()

		if (key.with === 'masterKey') {
			return masterKey
		}

		const keyJWK = await decryptTextSymFromTRPC(key.content, key.iv, masterKey)

		if (keyJWK instanceof Error) {
			return new Error('Failed to decode the second layer encryption key')
		}

		key = { with: 'jwk', content: keyJWK }
	}

	const imported = await importKeyFromTRPC(key.content, 'sym')

	if (imported instanceof Error) {
		return new Error('Failed to import the provided key')
	}

	return imported
}
